Add media queries to make the mobile version responsive on desktop sc…
KingKowa/Personal-Portfolio-MobileVersion pull request #5
Opened 2022-04-29 15:50 UTC by KingKowa

Added media queries to make sure the website displays correctly on desktop screens.

2022-04-29 18:45 UTC, ShahierNashaat requested changes
Hi @KingKowa , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 18:45 UTC, ShahierNashaat commented on index.html
>              </div>
- [ ] Please remove the bar at the top of the header and add a background image to the header.

Your design                       |Figma design               
:--------------------------------: | :-----------------------------------:
![Screenshot from 2022-04-29 20-32-30](https://user-images.githubusercontent.com/33752735/166006495-5d5255e4-72d2-4fe7-ac98-f31eb2887b8a.png)|![Screenshot from 2022-04-29 20-35-00](https://user-images.githubusercontent.com/33752735/166006525-e4756f51-7d2f-42c4-9408-1e78da2b401c.png)

2022-04-29 18:45 UTC, ShahierNashaat commented on styles.css
> +  }
- [ ] Kindly be noticed that there is a horizontal scroll in the desktop size of your portfolio so suggested changing the width in some divs from 1440px to 100% also remove some padding that causes this horizontal scroll.

![Screenshot from 2022-04-29 20-33-15](https://user-images.githubusercontent.com/33752735/166007029-ed2bbe4f-1941-4869-8f44-c52d54eb63bf.png)

2022-04-30 19:57 UTC, keroloussamy approved these changes
Hi @KingKowa, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)

## Optional suggestions
_Check the comments under the review._

- [ ] [OPTIONAL] On the mobile section there's an additional width you can delete it, to make your design perfect.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 20:31 UTC, merged